---
sidebar: sidebar 
permalink: information/additional_resources.html 
keywords:  
summary:  
---
= その他のリソース
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ここでは、 NetApp クラウドサービスとサポート、および REST とクラウドの一般的な概念について、ヘルプや詳細情報を参照するためのリソースを提供しています。



== アストラ

* https://["Astra Control Center 2108 のマニュアル"^]
+
お客様の施設に導入された Astra Control Center ソフトウェアのドキュメント。

* https://["Astra Control Service のマニュアル"^]
+
パブリッククラウドで利用可能な Astra Control Service ソフトウェアのドキュメント。

* https://["Astra Trident のドキュメント"^]
+
ネットアップが管理している Astra Trident オープンソースストレージオーケストレーションツールのドキュメント





== ネットアップのクラウドリソース

* https://["ネットアップのクラウドソリューション"^]
+
ネットアップのクラウドソリューションの中心的なサイト。

* https://["NetApp Cloud Central コンソール"^]
+
NetApp Cloud Central サービスコンソールにサインインします。

* https://["ネットアップサポート"^]
+
トラブルシューティングツール、ドキュメント、およびテクニカルサポートにアクセスできます。





== REST の概念とクラウドテクノロジ

* 博士 https://["失策"^] 著者 : Roy Fielding オリジナル版を読む
+
本ドキュメントでは、 REST アプリケーション開発モデルを導入および確立しました。

* https://["Auth0"^]
+
これは、 Astra サービスが Web アクセスに使用する認証および認可プラットフォームサービスです。

* https://["RFC エディタ"^]
+
独自に番号付けされた RFC 文書の集合として維持されている Web およびインターネット標準の信頼できるソース。


